name: Destroy Lambda Infra With Terraform

on:
  workflow_dispatch: # Manually trigger the workflow
   inputs:
    environment:
        description: " Select Environment to deploy (e.g., dev, staging, prod)"
        required: true
        default: "dev"
        type: choice
        options:
        - dev
        - staging
        - prod

jobs:
  destroy:
    name: Destroy Terraform Resources
    runs-on: ubuntu-latest

    # Define environment variables once for the whole job
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.5

      - name: Terraform Init
        run: | 
          cd infra/environments/${{ github.event.inputs.environment || 'dev' }}
          terraform init

      - name: Destroy Resources
        run: |
          cd infra/environments/${{ github.event.inputs.environment || 'dev' }}
          terraform destroy -auto-approve
